
-- EXEC O_SP_FILLDATASET 'Users' , 'Id,UserName' ,'' ,''
-- EXEC O_SP_FILLDATASET 'Users' , 'Id,UserName' ,"Id = '1' and UserName= 'Sabrina'",''

ALTER PROCEDURE O_SP_FILLDATASET
@TABLENAME varchar(MAX)
,@COLUMNAME varchar(MAX)
,@WHERECONDITION varchar(MAX) 
,@ORDERBY varchar(MAX)
AS
BEGIN
SET NOCOUNT ON;
DECLARE @SQL NVARCHAR(MAX);
DECLARE @COLUMNAME1 NVARCHAR(MAX);
DECLARE @TABLENAME1 NVARCHAR(MAX); 
DECLARE @WHERECONDITION1 NVARCHAR(MAX); 
DECLARE @ORDERBY1 NVARCHAR(MAX);

SET @COLUMNAME1=@COLUMNAME;
SET @TABLENAME1=@TABLENAME;
SET @ORDERBY1=@ORDERBY;
SET @WHERECONDITION1=@WHERECONDITION;

print @WHERECONDITION
print @ORDERBY

IF (@WHERECONDITION is null OR @WHERECONDITION='') AND (@ORDERBY is null OR @ORDERBY='') 
BEGIN
print '1'
SET @SQL='SELECT '+ @COLUMNAME1 + ' FROM ' + @TABLENAME1
END

ELSE IF (@WHERECONDITION is NOT null AND @WHERECONDITION<>'') AND (@ORDERBY is null OR @ORDERBY='') 
BEGIN
print '2'
SET @SQL='SELECT '+ @COLUMNAME1+ ' FROM '+@TABLENAME1 + ' WHERE '+ CONVERT(NVARCHAR(MAX), @WHERECONDITION1 ) 
END

ELSE IF (@WHERECONDITION is NOT null AND @WHERECONDITION<>'') AND (@ORDERBY is not null AND @ORDERBY<>'') 
BEGIN 
print '3'
SET @SQL='SELECT '+ @COLUMNAME1 + ' FROM ' + @TABLENAME1 + ' WHERE ' + CONVERT(NVARCHAR(MAX), @WHERECONDITION1) +  ' ORDER BY ' + @ORDERBY1
END

ELSE IF (@WHERECONDITION is null OR @WHERECONDITION='') AND (@ORDERBY is noT null AND @ORDERBY<>'')
BEGIN
print '4'
SET @SQL=' SELECT ' + @COLUMNAME1+ ' FROM ' +@TABLENAME1+ ' ORDER BY ' + @ORDERBY1
END

--PRINT @SQL new line execute(@SQL) new line PRINT @SQL
PRINT @SQL execute(@SQL)  PRINT @SQL

END